/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./public/**/*.{js,ts,jsx,tsx}",
    "./website/**/*.{js,ts,jsx,tsx}",
    "./website/src/**/*.{js,ts,jsx,tsx}",
    "./website/src/app/**/*.{js,ts,jsx,tsx}",
    "./website/src/components/**/*.{js,ts,jsx,tsx}",
    "./website/src/pages/**/*.{js,ts,jsx,tsx}",
    "./website/src/public/**/*.{js,ts,jsx,tsx}",
    "./website/src/styles/**/*.{js,ts,jsx,tsx}",
    "./website/src/assets/**/*.{js,ts,jsx,tsx}",
    "./website/src/utils/**/*.{js,ts,jsx,tsx}",
    "./website/src/hooks/**/*.{js,ts,jsx,tsx}",
    "./website/src/lib/**/*.{js,ts,jsx,tsx}",
    "./website/src/data/**/*.{js,ts,jsx,tsx}",
    "./website/src/features/**/*.{js,ts,jsx,tsx}",
    "./website/src/layouts/**/*.{js,ts,jsx,tsx}",
    "./website/src/services/**/*.{js,ts,jsx,tsx}",
    "./website/src/context/**/*.{js,ts,jsx,tsx}",
    "./website/src/store/**/*.{js,ts,jsx,tsx}",
    "./website/src/hooks/**/*.{js,ts,jsx,tsx}",
    "./website/src/components/**/*.{js,ts,jsx,tsx}",
    "./website/src/pages/**/*.{js,ts,jsx,tsx}",
    "./website/src/app/**/*.{js,ts,jsx,tsx}",
    "./website/src/styles/**/*.{js,ts,jsx,tsx}",
    "./website/src/assets/**/*.{js,ts,jsx,tsx}",
    "./website/src/utils/**/*.{js,ts,jsx,tsx}", 
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
